version: 2
updates:
  - package-ecosystem: "mix"
    directories:
      - "/api"
      - "/auth"
      - "/alert"
      - "/shared"
    schedule:
      interval: "weekly"
  - package-ecosystem: "bun"
    directory: "/web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
